"""add  confirmed to blocks

Revision ID: 00a6131d3fd2
Revises: 2c7844e9f58e
Create Date: 2025-12-29 17:15:07.151528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a6131d3fd2'
down_revision: Union[str, Sequence[str], None] = '2c7844e9f58e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blocks', 'confirmed')
    # ### end Alembic commands ###
