"""Add extra_nonce2, ntime, nonce fields to shares table

Revision ID: 00f766c2fbb0
Revises: 00a6131d3fd2
Create Date: 2026-01-03 23:41:54.903207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00f766c2fbb0'
down_revision: Union[str, Sequence[str], None] = '00a6131d3fd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shares', sa.Column('extra_nonce2', sa.String(length=16), nullable=True))
    op.add_column('shares', sa.Column('ntime', sa.String(length=16), nullable=True))
    op.add_column('shares', sa.Column('nonce', sa.String(length=16), nullable=True))
    op.alter_column('shares', 'difficulty',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shares', 'difficulty',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('shares', 'nonce')
    op.drop_column('shares', 'ntime')
    op.drop_column('shares', 'extra_nonce2')
    # ### end Alembic commands ###
