"""add is_valid field to shares

Revision ID: 2c7844e9f58e
Revises: 91bd05f171fc
Create Date: 2025-12-29 17:06:50.706228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c7844e9f58e'
down_revision: Union[str, Sequence[str], None] = '91bd05f171fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shares', sa.Column('is_valid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shares', 'is_valid')
    # ### end Alembic commands ###
