"""Add created_at to miners

Revision ID: 91bd05f171fc
Revises: 98d28ab7e67f
Create Date: 2025-12-29 10:35:32.062912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91bd05f171fc'
down_revision: Union[str, Sequence[str], None] = '98d28ab7e67f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miners', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('miners', sa.Column('total_shares', sa.Integer(), nullable=True))
    op.add_column('miners', sa.Column('total_blocks', sa.Integer(), nullable=True))
    op.add_column('miners', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('miners', sa.Column('hashrate', sa.Float(), nullable=True))
    op.drop_column('miners', 'registered_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miners', sa.Column('registered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('miners', 'hashrate')
    op.drop_column('miners', 'is_active')
    op.drop_column('miners', 'total_blocks')
    op.drop_column('miners', 'total_shares')
    op.drop_column('miners', 'created_at')
    # ### end Alembic commands ###
