"""Initial tables

Revision ID: 98d28ab7e67f
Revises: 
Create Date: 2025-12-26 17:40:14.110263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98d28ab7e67f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('miner_address', sa.String(length=128), nullable=False),
    sa.Column('found_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocks_found_at'), 'blocks', ['found_at'], unique=False)
    op.create_index(op.f('ix_blocks_hash'), 'blocks', ['hash'], unique=True)
    op.create_index(op.f('ix_blocks_height'), 'blocks', ['height'], unique=False)
    op.create_index(op.f('ix_blocks_id'), 'blocks', ['id'], unique=False)
    op.create_index(op.f('ix_blocks_miner_address'), 'blocks', ['miner_address'], unique=False)
    op.create_table('miners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bch_address', sa.String(length=128), nullable=False),
    sa.Column('worker_name', sa.String(length=64), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_miners_bch_address'), 'miners', ['bch_address'], unique=True)
    op.create_index(op.f('ix_miners_id'), 'miners', ['id'], unique=False)
    op.create_table('shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('miner_address', sa.String(length=128), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shares_id'), 'shares', ['id'], unique=False)
    op.create_index(op.f('ix_shares_miner_address'), 'shares', ['miner_address'], unique=False)
    op.create_index(op.f('ix_shares_submitted_at'), 'shares', ['submitted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shares_submitted_at'), table_name='shares')
    op.drop_index(op.f('ix_shares_miner_address'), table_name='shares')
    op.drop_index(op.f('ix_shares_id'), table_name='shares')
    op.drop_table('shares')
    op.drop_index(op.f('ix_miners_id'), table_name='miners')
    op.drop_index(op.f('ix_miners_bch_address'), table_name='miners')
    op.drop_table('miners')
    op.drop_index(op.f('ix_blocks_miner_address'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_id'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_height'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_hash'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_found_at'), table_name='blocks')
    op.drop_table('blocks')
    # ### end Alembic commands ###
